"""add response

Revision ID: 2f1fe8629953
Revises: 
Create Date: 2016-10-14 11:03:56.888965

"""

# revision identifiers, used by Alembic.
revision = '2f1fe8629953'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('path', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('response', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    ### end Alembic commands ###
